[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true

[program:cms]
command=node /app/scripts/cms-server.mjs
directory=/app
autorestart=true
environment=NODE_ENV="production"
